import Image from 'next/image'
import React from 'react'
import historyBanner from './../assets/historyBanner.jpg'
import Head from 'next/head'
import ServiceCardEnquiry from '../components/ServiceCardEnquiry'
import hardServicesImg from './../assets/hard_services.jpg'
import softServicesImg from './../assets/soft_services.jpg'
import managementServicesImg from './../assets/management_services.jpg'
import healthServicesImg from './../assets/healthServicesImg.jpg'
import propertyServicesImg from './../assets/propertyServicesImg.jpg'
import sterServicesImg from './../assets/sterServicesImg.jpg'
import MainTitle from '../components/MainTitle'

const services = () => {
  return (
    <>
      <Head>
        <title>History - Boualvard</title>
      </Head>

      <div className="container w-full h-full mx-auto px-10" >
        <div className="relative wrap overflow-hidden px-10 h-full">
          <MainTitle title="Our History" />
          <div
            className="border-2-2 absolute border border-golden z-10"
            style={{ left: '50%', top: '6%', height: "90%" }}
          ></div>
          <LeftTimeLine time='2005' content='Accordingly, the company name was changed to Basateen Foods Saudi Arabia Ltd. (BFSA) in 2005.' />
          <NodeTimeLine />
          <RightTimeLine time='2003' content='Part of Unilever Arabia group of companies till 2003, the company along with its major brand “Mazola” was acquired by Mr Abdullah Said Binzagr and partners late that year. The Bouillon production ceased late 2003, in accordance with the agreement with Unilever Arabia.' />
          <NodeTimeLine />
          <LeftTimeLine time='2000' content='Best Foods merged with Unilever in the year 2000.A bouillon manufacturing line capable of producing both pasty bouillon in pails and as cubes was installed in 2000.' />
          <NodeTimeLine />
          <RightTimeLine time='1998' content='The refinery process was changed in 1998 from full refining of crude oil to last stage process (deodorizing) only, leading to virtual elimination of wastewater generation in the refinery. The wastewater generated by the plant is now well within the RC specifications for industrial affluent. Following treatment, a significant part of the final wastewater is used for irrigation of vegetation within the site and the rest is released to the RC industrial affluent collection system.' />
          <NodeTimeLine />
          <LeftTimeLine time='1994' content='The processing and packaging line which also started producing Vegetable Ghee in 1994.' />
          <NodeTimeLine />
          <RightTimeLine time='1993' content='In 1993, a Margarine and Shortening processing and packaging line was installed. A biological Wastewater Treatment plant was set up in 1993 to treat all the liquid waste produced in the plant before releasing into Royal Commission (RC) industrial wastewater collection system.' />
          <NodeTimeLine />
          <LeftTimeLine time='1992' content='In 1992, a processing and packaging line for Mayonnaise/Dressings was started in a small way which grew over the years to a reasonable production capacity.' />
          <NodeTimeLine />
          <RightTimeLine time='1989' content='The company started with a head office in Jeddah and a manufacturing plant at Light Industrial Park, Yanbu Al-Sinaiyah (Yanbu Industrial City). The plant operation started in January, 1989 with a corn oil refinery, a blow molding line to manufacture plastic bottles for oil and an automatic oil filling line. Two small oil filling lines, a 1-liter bottle filling line and a catering oil filling line, were set up in the following years. The refinery operation was originally started as a four-stage complete refining of crude corn oil. The first stage, the caustic refining, generated significant quantity of high COD wastewater through treatment of soap stock, a by-product of caustic refining of oil. ' />
          <NodeTimeLine />
          <LeftTimeLine time='1988' content='Best Foods Saudi Arabia Ltd. (now BASATEEN FOODS) was established in 1988 as a joint venture between Beit Binzagr, a leading business house in the Kingdom of Saudi Arabia and former CPC International Inc., a multinational US food company that was rechristened Best Foods in 1998.' />
          <NodeTimeLine />
          <RightTimeLine time='1911' content='Mazola is originated from USA in 1911. With a century experience, Mazola has the expertise in producing premium corn oil, free of cholesterol and made of 100% pure and natural with no preservatives or additives.' />
        </div>
      </div>
    </>
  )
}

export default services

const NodeTimeLine = ({}) => {
  return (
    <div className="mb-8 flex justify-between items-center w-full right-timeline">
      <div className="order-1 w-5/12"></div>
      <div className="z-20 flex items-center order-1 border-gray-600 border-opacity-85 border-1 outline bg-white w-3 h-3 rounded-full outline-8 outline-white">
        <h1 className="mx-auto font-semibold text-lg text-white"> </h1>
      </div>
      <div className="order-1 w-5/12 px-6 py-4"></div>
    </div>
  )
}

const RightTimeLine = ({
  time = 'time',
  hasTitle = false,
  title = 'Title',
  content = "Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industry's standard dummy text ever since the 1500s, when an unknown printer took a galley of type and scrambled it to make a type specimen book.",
}) => {
  return (
    <div className="mb-8 flex justify-between items-center w-full right-timeline">
      <div className="order-1 w-5/12"></div>
      <div className="z-20 flex items-center order-1 w-8 h-8">
        <h1 className="mx-auto font-semibold text-lg text-golden bg-white z-20 py-3">
          {time}
        </h1>
      </div>
      <div className="order-1 w-5/12 px-6 py-4 bg-grayish mt-24 relative">
      <div className='absolute top-3 -left-2 w-6 h-6 -rotate-45 bg-grayish'></div>
        {hasTitle && (
          <h3 className="mb-3 font-bold text-gray-800 text-xl">{title}</h3>
        )}
        <p className="text-xxs md:text-sm leading-snug tracking-wide text-black text-opacity-100">
          {content}
        </p>
      </div>
    </div>
  )
}

const LeftTimeLine = ({
  time = 'time',
  hasTitle = false,
  title = 'Title',
  content = "Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industry's standard dummy text ever since the 1500s, when an unknown printer took a galley of type and scrambled it to make a type specimen book.",
}) => {
  return (
    <div className="mb-8 flex justify-between flex-row-reverse items-center w-full left-timeline">
      <div className="order-1 w-5/12"></div>
      <div className="z-20 flex items-center order-1 w-8 h-8">
        <h1 className="mx-auto font-semibold text-lg text-golden bg-white z-20 py-3">
          {time}
        </h1>
      </div>
      <div className="order-1 w-5/12 px-6 py-4 bg-grayish mt-24 relative">
        <div className='absolute top-3 -right-2 w-6 h-6 -rotate-45 bg-grayish'></div>
        {hasTitle && (
          <h3 className="mb-3 font-bold text-gray-800 text-md lg:text-xl">
            {title}
          </h3>
        )}
        <p className="text-xxs md:text-sm leading-snug tracking-wide text-black text-opacity-100">
          {content}
        </p>
      </div>
    </div>
  )
}
